project_id = "pxzwzayroweafcroouvc"

[functions.kalshi-validate]
verify_jwt = false

[functions.kalshi-markets]
verify_jwt = false

[functions.kalshi-events]
verify_jwt = false

[functions.kalshi-price-history]
verify_jwt = false

[functions.kalshi-portfolio]
verify_jwt = false

[functions.kalshi-trade]
verify_jwt = false

[functions.twitter-fetch]
verify_jwt = false

[functions.polymarket-markets]
verify_jwt = false

[functions.polymarket-portfolio]
verify_jwt = false

[functions.polymarket-trade]
verify_jwt = false

[functions.polymarket-price-history]
verify_jwt = false

[functions.search-related-markets]
verify_jwt = false

[functions.polymarket-create-api-key]
verify_jwt = false

[functions.polymarket-time]
verify_jwt = false

[functions.polymarket-smoke]
verify_jwt = false

[functions.polymarket-validate]
verify_jwt = false

[functions.polymarket-orders-active]
verify_jwt = false

[functions.polymarket-l2-keycheck]
verify_jwt = false
